#ifndef MIMECONSTANTS_H_
#define MIMECONSTANTS_H_
#pragma once

namespace attic { namespace cnst { namespace mime {

static const char* mime_types = 
    "audio/midi mid midi kar\n"
    "audio/mp4 aac f4a f4b m4a\n"
    "audio/mpeg mp3\n"
    "audio/ogg oga ogg\n"
    "audio/x-realaudio ra\n"
    "audio/x-wav wav\n"
    "audio/x-flac flac\n"
    "audio/x-aiff aif\n"
    "image/bmp bmp\n"
    "image/gif gif\n"
    "image/jpeg jpeg jpg\n"
    "image/png png\n"
    "image/tiff tif tiff\n"
    "image/webp webp\n"
    "image/x-icon ico\n"
    "image/svg+xml svg svgz\n"
    "video/3gpp 3gpp 3gp\n"
    "video/mp4 mp4 m4v f4v f4p\n"
    "video/mpeg mpeg mpg\n"
    "video/ogg ogv\n"
    "video/quicktime mov\n"
    "video/webm webm\n"
    "video/x-flv flv\n"
    "video/x-ms-asf asx asf\n"
    "video/x-ms-wmv wmv\n"
    "video/x-msvideo avi\n"
    "video/x-matroska mkv\n"
    "video/mp2t ts\n"
    "application/x-mpegurl m3u8\n"
    "application/javascript js\n"
    "application/json json\n"
    "application/msword doc\n"
    "application/vnd.ms-excel xls\n"
    "application/vnd.ms-powerpoint ppt\n"
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document docx\n"
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet xlsx\n"
    "application/vnd.openxmlformats-officedocument.presentationml.presentation pptx\n"
    "application/x-iwork-keynote-sffkey keynote\n"
    "application/x-iwork-pages-sffpages pages\n"
    "application/x-iwork-numbers-sffnumbers numbers\n"
    "application/xml atom rdf rss xml\n"
    "application/font-woff woff\n"
    "application/vnd.ms-fontobject eot\n"
    "application/x-font-ttf ttc ttf\n"
    "font/opentype otf\n"
    "application/java-archive jar war ear\n"
    "application/pdf pdf\n"
    "application/postscript ps eps ai\n"
    "application/rtf rtf\n"
    "application/xhtml+xml xhtml\n"
    "application/vnd.google-earth.kml+xml kml\n"
    "application/vnd.google-earth.kmz kmz\n"
    "application/x-7z-compressed 7z\n"
    "application/x-chrome-extension crx\n"
    "application/x-opera-extension oex\n"
    "application/x-xpinstall xpi\n"
    "application/x-java-archive-diff jardiff\n"
    "application/x-java-jnlp-file jnlp\n"
    "application/x-rar-compressed rar\n"
    "application/x-shockwave-flash swf\n"
    "application/x-x509-ca-cert der pem crt\n"
    "application/zip zip\n"
    "application/gzip gz\n"
    "application/bzip2 bz2\n"
    "application/tar tar\n"
    "text/css css\n"
    "text/csv csv\n"
    "text/html html htm shtml\n"
    "text/mathml mml\n"
    "text/plain txt\n"
    "text/vnd.sun.j2me.app-descriptor jad\n"
    "text/vnd.wap.wml wml\n"
    "text/vtt vtt\n"
    "text/x-component htc\n"
    "text/x-vcard vcf\n\0";

}}}//namespace

#endif

